"""Constants for the TSUN integration."""

DOMAIN = "tsun"
CONF_LOGGER_SN = "logger_sn"
CONF_INVERTER_SN = "inverter_serial_number"
CONF_FIRMWARE_VERSION = "firmware_version"
CONF_MAC_ADDRESS = "mac_address"
CONF_DISCOVERY_NETWORK = "discovery_network"
CONF_ERROR_SCAN_INTERVAL = "error_scan_interval"
CONF_NIGHT_SCAN_INTERVAL = "night_scan_interval"
CONF_FAILURE_THRESHOLD = "failure_threshold"
DEFAULT_PORT = 8899
DEFAULT_SCAN_INTERVAL = 20
DEFAULT_ERROR_SCAN_INTERVAL = 20
DEFAULT_NIGHT_SCAN_INTERVAL = 300
DEFAULT_FAILURE_THRESHOLD = 3
MIN_SCAN_INTERVAL = 10
MAX_SCAN_INTERVAL = 300
MIN_NIGHT_SCAN_INTERVAL = 60
MAX_NIGHT_SCAN_INTERVAL = 3600
MIN_FAILURE_THRESHOLD = 1
MAX_FAILURE_THRESHOLD = 20
MANUFACTURER = "TSUN"
